### ISSUE TITLE
(refactor) convnet() in models.py is causing gpu to segfault

### ISSUE THREAD

**Issue by lmcintosh** [baccuslab/deep-retina#1]
Likely just a mismatch in input/output sizes, but it's annoying to track down

**Comment by anayebi** [comment]
Oh are you trying to train the convnet on lenna? Is the error you're getting some big splurge of text that says "failed to allocate such and such amount of memory"? If so, it's because I'm training the 2 convnets on lenna at the moment, so there isn't much more gpu memory left over. Try reducing your batch size to 50 or something. If that doesn't work, I can stop training the two convnets as well.

**Comment by lmcintosh** [comment]
No, this is just on my local machine, and it's a dimension mismatch error
I'm getting not a memory issue. Pretty sure it's a input/output issue in
the layer's I'm adding to the model, but tricky to troubleshoot in the
abstract way I refactored the model.


--
Lane McIntosh
www.lanemcintosh.com

**Comment by anayebi** [comment]
Ok, then the issue likely is your first Dense layer (called after Flatten). Since the images are 50x50 it should be:

model.add(Dense(13456, 32))

Instead of model.add(Dense(6400, 32)) as we had in the old stimulus case of 32x32.

**Comment by lmcintosh** [comment]
I don't hardcode any of my numbers, so I don't think it's likely that; I
just checked and my model trains just fine for 2 layers, but not for 3
layers, so it must be something about having an intermediate dense layer
that I miscoded.


--
Lane McIntosh
www.lanemcintosh.com

**Comment by lmcintosh** [comment]
Fixed issue - forgot to keep input dimensions 1x1 after all affine layers
